### ISSUE TITLE
[Question] Swift New Build System can't handle R.swift on Travis

### ISSUE THREAD

**Issue by Drwalcore** [mac-cain13/R.swift#372] opened 2017-12-12 13:08 UTC
As in title, I've turned on New Build System on my repository, but it has failed with following error:
```
❌  error: missing input '/Users/travis/build/drwalcore/trckr/R.generated.swift' and no rule to build it
❌  error: cannot build '/Users/travis/Library/Developer/Xcode/DerivedData/trckr-fobgqgzdhufvsjbtgcuwuruufjhf/Build/Intermediates.noindex/trckr.build/Debug-iphonesimulator/trckr.build/Objects-normal/x86_64/AppDelegate.o' due to missing input
```

I've run and tested it locally and R.swift was processed flawlessly. Maybe it's not R.swift related, so I am sorry for that 🤖 
After turning  off **New Build System** it is working again!

**Comment by tomlokhorst** [comment] 2017-12-12 13:39
I don't have any experience with R.swift + Travis. But like you I can build with R.swift and the New Build System just fine.

So I'm assuming that this is indeed a Travis issue.
Are you sure Travis is doing a clean build? Or is it reusing cached build results from a previous build with the Standard Build System?

**Comment by Drwalcore** [comment] 2017-12-12 13:44
Thank You for a response, I will look for issues on Travis side. I am pretty sure Travis CI makes a clean build every time the build starts. I will make some research,  and I will be really glad to help to resolve this issue, to be prepared for official New Build System usage along with R.swift and Travis duo!

**Comment by HelloCore** [comment] 2017-12-25 10:35
I found this problem too. I believed the problem is you didn't keep R.generated.swift in your repository. You can reproduce this by deleting R.generated.swift and choosing New Build System then it will build fail on 1st time and it will build success on the next time.

**Comment by Drwalcore** [comment] 2017-12-27 08:19
This is a clever solution, thank You for the response. I will definitely give it a try.

**Comment by mac-cain13** [comment] 2018-02-07 15:49
Assuming that this is solved now, so I will close this one.

**Comment by AwaisFayyaz** [comment] 2018-08-13 07:43
how to  add rswift generate in your build script.?

**Comment by Drwalcore** [comment] 2018-08-13 07:45
@AwaisFayyaz what do You mean? Everything is written there...
https://github.com/mac-cain13/R.swift#cocoapods-recommended

**Comment by AwaisFayyaz** [comment] 2018-08-13 12:01
I had another "missing input" error. I was confused with this. sorry, removed my comment. you can also remove your reply. after that i will remove this message. 

BTW, i just learned about R.swift. Cool

**Comment by Drwalcore** [comment] 2018-08-13 12:04
No worries :)!

Z poszanowaniem,
Michał.

**Comment by fabb** [comment] 2018-09-20 15:55
Adding generated source files to the repo is not a nice solution.
Better solution: in the run script phase just specify the generated file as an output file. That will satisfy the new Xcode build system which needs that information to properly parallelize and schedule build tasks.

**Comment by mac-cain13** [comment] 2018-09-21 19:49
We observe that adding _only_ the output file is not enough. It will fix running R.swift on a clean build. But on a incremental build it will still fail to detect changes.

I don't understand why Xcode 10 makes the assumption this is okay. I would think that no inputs defined means that we should be runned always, but it seems that is not the case. So I'm affraid we need to generate input file lists.

**Comment by fabb** [comment] 2018-09-21 21:36
Urgs. That sounds like a bug we should file a Radar for. 

In session 408, Apple was pretty clear about when no input files were declared, that the build phase would always be run.



https://developer.apple.com/wwdc18/408

**Comment by tomlokhorst** [comment] 2018-11-28 20:17
Note that only adding R.generated.swift as an Output File to the R.swift build step is not sufficient.
As this means the builds step is only run once during incremental builds. Since the output file already exists in subsequent builds.

For continued discussion on this topic, see: 
https://github.com/mac-cain13/R.swift/issues/456

**Closed by tomlokhorst** 2018-11-28 20:17 UTC
