### ISSUE TITLE
Proposal: localization namespaces

### ISSUE THREAD

**Issue by ky1vstar** [mac-cain13/R.swift#481] opened 2019-01-05 15:13 UTC
Now if you want to separate localization files to layers, you should create different *.strings files. But I've found it complicated to localize all of this strings files. If, for example, in Main.strings I specified key pair such as `welcome.title = "Hello world";` and then could access it like `R.string.main.welcome.title` instead of `R.string.main.welcomeTitle`, it would be nice.

**Comment by luolong** [comment] 2019-01-21 11:03
Isn't this a duplicate of #402 ?

**Comment by tomlokhorst** [comment] 2019-01-21 13:04
Yes this is duplicate. I'll close this one, in favour of #402

**Closed by tomlokhorst** 2019-01-21 13:04 UTC
