### ISSUE TITLE
SWRevealViewController Storyboard

### ISSUE THREAD

**Issue by piv199** [mac-cain13/R.swift#291] opened 2016-12-01 09:57 UTC
I've done as Q&A sections says, but I got an error! What to do... Urgh......

<img width="260" alt="screen shot 2016-12-01 at 11 56 21" src="https://cloud.githubusercontent.com/assets/8293191/20789484/45bec7ae-b7bd-11e6-958e-5482c71e78c9.png">

<img width="761" alt="screen shot 2016-12-01 at 11 56 35" src="https://cloud.githubusercontent.com/assets/8293191/20789487/491755e2-b7bd-11e6-9242-4206f4fd6cd4.png">

Any workaround?

**Comment by piv199** [comment] 2016-12-01 10:44
<img width="812" alt="screen shot 2016-12-01 at 12 43 49" src="https://cloud.githubusercontent.com/assets/8293191/20791056/dcfd6bba-b7c3-11e6-9b1b-16e082aed8a4.png">

What's this? I have done as you suggest, but it always fails the build, neither for SWRevealViewController and SlideMenuController

**Comment by mac-cain13** [comment] 2016-12-03 16:33
The first one is a bug in the Swift compiler: https://bugs.swift.org/browse/SR-898 When a type has the same name as the module it is in you get an error when you reference it. Can you use this type from code in other places? What syntax do you use if it works?

The second error could be the same problem, does `SideMenuController` have a type that has the same name as it's module? If that's not the case it could be that it is linked incorrectly.

**Comment by mac-cain13** [comment] 2016-12-03 16:36
Another thought; Maybe this broke since we started using fully qualified names. Could you give R.swift 3.0.0 a try and let me know if that does work? Then you're probably hitting the same issue as the persons reporting problems here: https://github.com/mac-cain13/R.swift/issues/277

**Comment by mac-cain13** [comment] 2016-12-05 07:05
So after some research this issue seems to be a duplicate of #277. Let's move the discussion to over there and close this one.

Thanks for reporting!

**Closed by mac-cain13** 2016-12-05 07:05 UTC
Labels: state: awaiting input
