### ISSUE TITLE
R.swift doesn't pick up colorset assets in xcassets files

### ISSUE THREAD

**Issue by xmanu** [mac-cain13/R.swift#445] opened 2018-09-07 10:02 UTC
Hi,

In my project R.swift 4.0.0 doesn't seem to pick up any colorsets. Even if they are defined in the same xcassets file that contains images that are picked up by R.swift.

Any idea how I can debug this, or what could be the issue?

**Comment by mac-cain13** [comment] 2018-09-12 06:01
Thanks for using R.swift, strange this is not working while the images are picked up. Would you be able to reproduce this in an example project that you can share with us? Then we can look into this.

Maybe there is something with the color asset that makes R.swift skip it (there should be a warning about this), but other then that I can't think about obvious reasons this doesn't work if you're seeing images from the same asset catalog in the generated file.

**Comment by xmanu** [comment] 2018-09-21 13:44
I don't know how this happened. But deleting the generated file fixed it. The next full rswift run generated the R.color. instances...

**Comment by tomlokhorst** [comment] 2018-10-01 13:41
Can you check if this is related to the New Build System issues? See: https://github.com/mac-cain13/R.swift/issues/456

**Comment by xmanu** [comment] 2018-10-01 14:28
This issue happened with XCode 9 and the old build system. (Un)fortunately I didn't run into the issue again, so I can't reproduce it or give more details...

**Comment by tomlokhorst** [comment] 2018-10-02 13:30
Ok, thanks for the update.

Since you can't reproduce the problem, I'm going to close this issue.
If this pops up again, please don't hesitate to leave a comment, or open a new issue.

**Closed by tomlokhorst** 2018-10-02 13:30 UTC
