### ISSUE TITLE
UIImage convenience none-optional initialisation method

### ISSUE THREAD

**Issue by andreyslyusar** [mac-cain13/R.swift#109] opened 2015-11-02 13:19 UTC
Maybe R.swift should support UIImage convenience none-optional init method, similar to SwiftGen:
```
extension UIImage {
    enum Asset : String {
        case Apple = "Apple"
        case Banana = "Banana"
        
        var image: UIImage {
            return UIImage(asset: self)
        }
    }
    
    convenience init!(asset: Asset) {
        self.init(named: asset.rawValue)
    }
}
```

What do you think? Are they any possibility image will be not initialised, in case we sure resource with current name exists?

**Comment by mac-cain13** [comment] 2015-11-02 13:44
There are valid cases where a statement like `R.image.appleLogo` returns `nil`, for example when you only put a Apple Watch only images into your iOS app and try to load it or when you use On Demand Resources and the image hasn't been loaded yet.

So yes, 90% of the time you could use a convenience method that does a force unwrap, but I don't want R.swift to be the cause of any crashes. If you feel the Apple logo is always available you can easily do the unwrap yourself by using: `R.image.appleLogo!`

This makes it the developers responsibility to force unwrap, and makes it explicit what's happening. I don't really see any benefit when R.swift does this for you.

Considering this, what would the win be according to you? Could you provide a use case?

**Comment by andreyslyusar** [comment] 2015-11-02 14:57
I just get a feeling in case we can guarantee availability of the image resource it should be none-optional initializer. I will setup project in the evening and play around.

**Comment by andreyslyusar** [comment] 2015-11-12 20:46
I finally find time to play around and find that there a couple of case in which UIImage will be nil:
1. Any on-demand images 
2. Assets 'image set' without images
3. Broken image imported directly to xCode (not using Assets catalog)

It means support UIImage convenience none-optional init method is not save for all kind of resources. Should it be considered to add this init only for 100% image resources ? 

As a side effect I find it will be also nice to add support for `` On Demand Resource Tags ``. I will create corresponding issue.

**Comment by mac-cain13** [comment] 2015-11-30 07:58
Thanks for taking the time to do some research and sorry for replying so late.

I think that there are to many conditions in play to see if an image would always load. I want R.swift should never cause a crash I'm not willing to take the risk, especially since it is so easy to make it "non-optional" yourself by putting an `!` at the end of `R.image.myImage`.

And yes, resource tags should get into R.swift! It's on the list here: #48, I got started on this but we have to parse the json files in the Asset folder for this, since the project file is not kept up to date by Xcode. :(

**Comment by mac-cain13** [comment] 2015-12-07 21:14
Going to close this for now, if someone has a great idea how to make non-optional images without the risk of crashing I'd love to hear about it. So feel free to comment in that case.

**Closed by mac-cain13** 2015-12-07 21:14 UTC
Labels: state: awaiting input, type: discussion

**Comment by MattW86** [comment] 2019-02-17 23:04
Hi @mac-cain13,
How about implementing something like R.unsafeImage.appleLogo? This will explicitly unwrap the image. Cheers..
