### ISSUE TITLE
Preferred language fails on device

### ISSUE THREAD

**Issue by ncltg** [mac-cain13/R.swift#307] opened 2017-03-15 12:01 UTC
I'm having an issue with the default language on my phone : 

My project contains 3 languages : base, en, fr.
When testing on the simulator everything works fine, every language is detected correctly.

But when testing on a real device set to French as the preferred language, R.swift loads the Base language instead of French

Here is a little test i ran on the concerned device : 

```
print(Locale.preferredLanguages) // ["fr-FR", "en-FR"]
print(R.string.main.nav_title.bundle.localizations) // ["Base", "en", "fr", "fr_FR"]
print(R.string.main.nav_title.bundle.preferredLocalizations) // ["fr_FR", "fr"]
print(Locale.current) // fr_FR (current)
```

I tried different setup but can't get the french translation out of R.swift. :(

Is there a way to manually set a preferred language other than the current iPhone Locale, as the `hostingBundle` is a `fileprivate var` ?

Thanks for your help.

**Comment by tomlokhorst** [comment] 2017-03-15 13:41
I have a similar setup in my app (but with Dutch instead of French).
However, I can't reproduce this issue. Based on your description, it should work correctly.

Can you test the version without R.swift? `NSLocalizedString("nav_title", tableName: "main")`

Note:
In an app you can override the systems default language, by writing to the UserDefaults:
`UserDefaults.standard.setValue(["en"], forKey: "AppleLanguages")`
This value should be set when the application is loaded, so it will only be used when the app restarts.

You can also provide an Application Language in you Xcode scheme:
![screen shot 2017-03-15 at 14 38 05](https://cloud.githubusercontent.com/assets/75655/23951060/52b3ff8e-098d-11e7-871a-bebeecbdc98f.png)

**Comment by ncltg** [comment] 2017-03-15 14:19
Thanks for the help !

Following your suggestion i tried that:

```
print(NSLocalizedString("nav_title", tableName: "Main", comment: "")) // My english title
print(R.string.main.nav_title()) // My english title

print(Locale.current) // fr_FR (current)
```

Device is still in french, yet the output prints in English in both cases.
The run option app language is set to System Language, so its not coming from here.

But now I guess it's a `NSLocalizedString` related issue, not really a R.swift problem. :)

**Comment by tomlokhorst** [comment] 2017-03-20 07:51
Since this issue isn't related to R.swift, I'll close it.

Feel free to let us know if you fix your issue! It may be interesting to know what happened here.

**Closed by tomlokhorst** 2017-03-20 07:51 UTC

**Comment by ncltg** [comment] 2017-03-20 17:16
I'm still working on fixing this problem and actually the main bundle is working fine :

I tried to print a LocalizedString from the Localizable.strings and it works fine no matter the language, both in the device and the simulator. Which leads me to believe that it is indeed related to the way the hostingBundle is handled. I don't know which additional tests to run though.

```
print(NSLocalizedString("test_string", tableName: nil, bundle: Bundle.main, value: "", comment: "")) // prints in the correct language
print(R.string.main.test_string()) // Prints in base language
print(NSLocalizedString("test_string", tableName: "Main", comment: ""))  // Prints in base language

```

Have you any idea for me to fix it ?

**Comment by tomlokhorst** [comment] 2017-03-20 17:27
Can you post a stripped down version of your project that reproduces this issue so I can take a look at it?

**Comment by ncltg** [comment] 2017-03-20 17:42
Unfortunately this is a pretty heavy app (hundreds of files), it would be hard to strip it down while keeping it working.

When i run it with System language set in Application Language in the run scheme the base language is always sent back. If I force a language (French, English or else), everything works fine with R.swift and NSLocalizedString.

Sounds pretty strange to me and I having a hard time to find people with a similar problem on StackOverflow or in your previous issues.

I'll try to run the project on another computer and see if it's related to my Xcode for some reason, it really is the last solution I see for now.

Thanks for your help though !
