### ISSUE TITLE
SMP Intergarion Xcode 14.3 Plugin troubles 

### ISSUE THREAD

**Issue by N0t2Day** [mac-cain13/R.swift#823] opened 2023-04-10 21:27 UTC
Hey. I read solution for previous issue, but it didn't help me. I clone my project from git which already contains R.swift dependency. 
I tried remove R.swift from SPM and install again, it didn't help me.
Now I see next: 
<img width="245" alt="Screenshot 2023-04-11 at 00 26 14" src="https://user-images.githubusercontent.com/23290834/231002159-9f8a880f-86a2-48ff-a690-9124f88712b0.png">
<img width="551" alt="Screenshot 2023-04-11 at 00 26 31" src="https://user-images.githubusercontent.com/23290834/231002200-99cccc11-aeee-4f9c-b1eb-7f9fa3c5c753.png">

**Comment by MichaelCampbell** [comment] 2023-04-11 17:03
This solution worked for me: https://github.com/mac-cain13/R.swift/issues/813#issuecomment-1457045537

**Comment by tomlokhorst** [comment] 2023-04-16 21:35
Duplicate of https://github.com/mac-cain13/R.swift/issues/822

**Closed by tomlokhorst** 2023-04-16 21:35 UTC
