### ISSUE TITLE
Error in Xcode 11b4 Projects with SPM Packages

### ISSUE THREAD

**Issue by robfeldmann** [mac-cain13/R.swift#536] opened 2019-07-28 00:44 UTC
Hello,

I am trying to use R.swift (`5.1.0.alpha.4`) in an **Xcode 11b4** project that includes a local SPM Package. Similar to #419, at compile time, I get the following **error**:

> error: [R.swift] Project file at 'file:///.../R.swiftTest/R.swiftTest.xcodeproj/' could not be parsed, is this a valid Xcode project file ending in *.xcodeproj?
> The operation couldn’t be completed. (XcodeEdit.AllObjectsError error 0.)

Using the current stable version of R.swift (`5.0.3`) in the same exact project, at compile time, I get the following **warning**:

> warning: [R.swift] project.pbxproj is internally inconsistent.
>  -XCSwiftPackageProductDependency (D4D02E0622ED224E00F80FC8) is not used
> Perhaps a merge conflict?

Are projects with Packages not yet supported in [XcodeEdit](https://github.com/tomlokhorst/XcodeEdit)?

I have [attached a demo project](https://github.com/mac-cain13/R.swift/files/3438740/R.swiftTest.zip) which is using `5.1.0.alpha.4` and has the aforementioned error.

Thanks for your time!

**Comment by tomlokhorst** [comment] 2019-07-28 08:20
Thanks for you demo project. That helps a lot!
I had only tested SPM with remote packages, not with local packages. I've created a fix and this will be in the next alpha release.

The current stable version of R.swift doesn't support Packages.
R.swift 5.1 should ship with support for packages, around the time of the Xcode 11 GM.

**Comment by robfeldmann** [comment] 2019-07-28 20:09
Thanks @tomasharkema for your super quick response! I can also confirm your update to XcodeEdit did the trick. I really appreciate it.

**Comment by tomlokhorst** [comment] 2019-10-22 10:08
R.swift 5.1 has just been released.

**Comment by dwhitla** [comment] 2019-11-08 02:07
This doesn't appear to have been completely fixed in 5.1.0. Still get the spurious warning. It would be nice if I could silence it as we treat warnings as build failures.

**Comment by dwhitla** [comment] 2019-11-08 02:17
I should elaborate. The warning occurs when I use have a build time remote SPM dependency - in this case **R.swift**. I have made **R.swift** and **R.swift.library** dependencies of my primary artefact. This ensures that the **rswift** executable is built before any build phase scripts are executed. I am executing this **rswift** in a build phase script thus
`${SYMROOT}/Release/rswift" generate "${SRCROOT}/Generated/Sources/R.generated.swift`
**rswift** sees its own dependency and complains that `
[R.swift] project.pbxproj is internally inconsistent.
 - XCSwiftPackageProductDependency (FE0BD9D423709BD100796FC6) is not used
Perhaps a merge conflict?`
`
...
        FE0BD9D523709BD100796FC6 /* PBXTargetDependency */ = {
            isa = PBXTargetDependency;
            productRef = FE0BD9D423709BD100796FC6 /* rswift */;
        };
...
`

**Comment by ykotov2** [comment] 2019-12-21 13:51
I have the same issue too. My project contains local SPM library as one of its dependencies. And after executing R.swift build phase it outputs:
> warning: [R.swift] project.pbxproj is internally inconsistent.
>
> - XCSwiftPackageProductDependency (22C45CC5238C0E0E00D3DF02) is not used
>
>Perhaps a merge conflict?

Xcode version is 11.3 (11C29).

**Comment by ykotov2** [comment] 2020-04-23 07:32
The same still happens in Xcode 11.4 using R.swift 5.2.0:

> warning: [R.swift] project.pbxproj is internally inconsistent.
>
> - XCSwiftPackageProductDependency (46FA930623CF382B00C537BC) is not used
> - XCSwiftPackageProductDependency (50DB27782428FC330058C7C4) is not used
> - XCSwiftPackageProductDependency (50E1492723F7FC5D006D9BF7) is not used
>
> Perhaps a merge conflict?

**Comment by mac-cain13** [comment] 2020-04-23 09:29
Thanks for reporting this, can you create a small Xcode project and share that with us so we can reproduce and fix the issue? (Or confirm that the sample the initial reporter of this issue is still failing.)

That gives me a concrete starting point to investigate and fix things.

**Comment by advantis** [comment] 2020-04-23 16:02
Looks like the original reporter's sample works just fine. I'll try to detect what affects the issue and put together another sample soon.

**Comment by dwhitla** [comment] 2020-04-24 00:46
Try building R.swift itself as an SPM dependency of your project - that triggers it without fail.

**Comment by tomlokhorst** [comment] 2020-04-24 11:39
Thanks for your comment. I've now been able to reproduce the issue.

**Closed** 2020-04-25 11:41 UTC
