### ISSUE TITLE
Cannot use R.swift in a cocoapod lib

### ISSUE THREAD

**Issue by MartinMoizard** [mac-cain13/R.swift#293] opened 2016-12-08 17:28 UTC
I am building a framework that uses R.swift internally. When the library is used, all the image created by R.swift are `nil` (because it cannot find the good Bundle).

After reading http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/, I learnt that the appropriate way to reference the bundle of my framework is to use `NSBundle(for: <#ClassFromMyFramework#>)`.

I tried modifying the `R.generated.swift` file like this:

```
//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

private class RswiftDummy {}

/// This `R` struct is generated and contains references to static resources.
public struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: RswiftDummy.self) ?? Bundle.main
[...]
}
```

What do you think? Thank you.

**Comment by mac-cain13** [comment] 2016-12-09 08:00
The generated code tries to load the correct bundle by using `Bundle(identifier:)` and will use that for all image loading for example. Is the identifier you've assigned to your library used by R.swift? If so it should work.

We could switch from `Bundle(identifier:)` to `Bundle(for:)` if it turns out that loading based on identifier doesn't work in some cases. But I'd like to know when and why it isn't working for you.

**Comment by MartinMoizard** [comment] 2016-12-09 08:20
I checked, the identifier used by R.swift is the one set by my library (PRODUCT_BUNDLE_IDENTIFIER). It works when I run the code within the project of the library, but when I use the library as a dependency of another project, it fails.

Would you be interested in a sample reproducing this issue?

**Comment by mac-cain13** [comment] 2016-12-09 08:31
Are you using Cocoapods? I'm just checking another project I'm working on and I now notice all pods get identifiers with the pattern `org.cocoapods.[NAME_OF_POD]`. That could be the problem you're running into now.

Please let me know if this is the same as your problem, not too hard to fix if it is this. So when we're certain about the cause I'll release a version with a fix!

**Comment by MartinMoizard** [comment] 2016-12-09 08:57
Great, thanks a lot :) How are you planning to fix it?

**Comment by mac-cain13** [comment] 2016-12-09 09:22
Probably your proposed solution; using bundle loading based on a class instead of identifier based loading.

**Comment by MartinMoizard** [comment] 2016-12-09 11:10
Do you know when the fix is going to be available (just to know if I should find a temporary solution in the meantime)? Thanks

**Comment by mac-cain13** [comment] 2016-12-09 11:43
I'll release a new version this weekend. :)

**Comment by mac-cain13** [comment] 2016-12-10 13:06
I've pushed a fix to master, will be in the next release!

**Closed by mac-cain13** 2016-12-10 13:06 UTC
Labels: type: issue
